### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by hichemfantar** [nuxtlabs/nuxtlabs.com#56]
I've noticed that there is no license for this project. I suggest that a license be added such MIT or GPL-2.0 to allow people to make use of the project without worrying about legal complications.

I hope that you take this into consideration in the spirit of open source.

Thank you.

**Comment by Atinux** [comment]
Here you go: https://github.com/nuxtlabs/nuxtlabs.com/blob/main/LICENSE

:white_heart:

**Comment by hichemfantar** [comment]
Thank you 🚀
